baseURL = 'https://alexpang.cn/fe-interview'
languageCode = 'en-us'
title = '子洋前端题库'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false