name: '🐛 Bug Report / 题目纠错'
description: 'Report incorrect questions or answers / 反馈题目错误或答案不准确'
title: '[Bug]: '
labels: ['bug']
body:
  - type: dropdown
    attributes:
      label: 'Error Type / 错误类型'
      options:
        - 'Incorrect question stem / 题干错误'
        - 'Wrong answer / 答案错误'
        - 'Code example error / 代码示例错误'
        - 'Misclassification / 题目分类错误'
        - 'Terminology error / 术语错误'
        - 'Other / 其他'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Question Path / 题目路径'
      description: 'Full Markdown file path / 完整的Markdown文件路径'
      placeholder: |
        content/docs/javascript/closure.md
        content/docs/react/hooks/use-state.md
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Error Description / 错误描述'
      description: 'Describe the specific error and expected correct content / 具体描述错误表现及正确内容'
      placeholder: |
        ### Example / 示例:
        - 题干中「闭包的定义」描述不准确，ECMAScript规范中实际定义为...
        - 参考答案未处理Date对象克隆，正确实现应包含...
        - 该题目应归类到「浏览器原理」而非「JavaScript基础」
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Suggested Correction / 建议修正内容'
      description: 'Provide corrected content in Markdown format / 使用Markdown格式提供修正内容'
      placeholder: |
        ```markdown
        ## 参考答案

        ```javascript
        function deepClone(obj, map = new WeakMap()) {
          if (obj instanceof Date) return new Date(obj)
          // 修正后的实现...
        }
        ```
        ```
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'References / 参考资料'
      description: 'Official documentation or authoritative references / 官方文档或权威参考资料'
      placeholder: |
        - [MDN Closure Documentation](https://developer.mozilla.org/...)
        - 《JavaScript权威指南》第7章 P.205
        - ECMAScript 2023 Specification Section 15.8.4
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'Screenshots / 问题截图'
      description: 'Upload screenshots highlighting the issue (optional) / 上传问题截图（可选）'
      placeholder: |
        ![错误示例](https://via.placeholder.com/600x400.png?text=截图示例)
        ![修正建议](https://via.placeholder.com/600x400.png?text=对比示例)
